### ISSUE TITLE
Checklist pass payment

### ISSUE THREAD

**Issue by Jerome-CM** [Jerome-CM/BugsPointer#119]
- [x] Accédez à l'url recapPayment
- [x] Avoir les infos connues d'inscrites
- [x] le passage de Free à Free n'est pas possible
- [x] Le passage de Free à Target enmene bien à iban
- [x] les faux iban/bic sont en erreur
- [x] les vrai iban/bic enmene à Thanks
- [x] les données en bdd sont bonne
- [x] reprendre Target avec le Target produit une erreur
(target avec target l'erreur reste sur recap, freee avec free renvoie vers le dashboard )
- [ ] Repasser à Free change la bdd et cloture le subcribe mais pas le mandat
- [ ] Repasser à Target affiche le recap avec les infos d'adresse
- [ ] Si l'iban change on delete l'ancien mandat et on en refait un

**Comment by Jerome-CM** [comment]
Traité : le retour Free met bien la BDD à jour et annule la souscription sans supprimer le mandat, le retour Target préremplit les informations d'adresse, et la logique IBAN/BIC révoque désormais l'ancien mandat avant d'en créer un nouveau si les coordonnées bancaires changent.
